services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: mfmfahy/addressing-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-customer360}:${POSTGRES_PASSWORD:-customer360}@host.docker.internal:5432/customer360
      - PYTHONUNBUFFERED=1
      - AUTH_ENABLED=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: []
    restart: unless-stopped
    networks:
      - internal

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: mfmfahy/addressing-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    driver: bridge
